Docusaurus 2.0.1 + GraphQL API Reference
aserto-dev/aserto-docs pull request #80
Opened 2022-08-22 17:42 UTC by ronenh

This PR:
* Upgrades Docusaurus to v2.0.1
* Use [`graphql-markdown`](https://github.com/graphql-markdown/graphql-markdown) to generated API Reference documentation for the v2 directory GraphQL API.

2022-08-22 23:28 UTC, ogazitt commented
Nice work!

It's nice to have the autogenerated schema, but I think we do need some conceptual overview information. Noticed that this PR removes the overview page but I think that rather than removing it, we should expand on it.

Also, all the links within schema elements (e.g. http://localhost:3000/schema/enums/flag) are computed relative to "/schema" being at the root of the documentation, but the root is in fact /docs/directory-guide/graphql/reference/schema/".

Speaking of the location, I think we ought to have this be a top-level node (Directory API Reference) at the bottom of the sidebar (below the Troubleshooting). We can link it from a topic under "Directory Guide" called "API Reference". We can also link it from the topic called "API Reference" which has a link to readme.io, and could have a link to the graphql API as well.

Finally, I do think that the Directory Guide topic ought to have a set of sub-topics that show examples of how to create object types, relation types, object instances, relation instances.

As a guiding example, the guide could show how to implement a multi-tenant RBAC authorization scenario:
* create an "Organization" object type
* create an organization called "The Smiths"
* query for object instances of object type "Organization"
* create "viewer", "member", "owner" relation types on Organization
* connect the Citadel IDP (if you haven't already)
* create a relation of relation type "org-owner" between "The Smiths" and "Rick"
* create a relation of relation type "org-viewer" between "The Smiths" and "Morty"
* query for object instances of type "Organization", this time with the relations 

(and show the full GraphQL mutations / queries / results)

2022-08-23 00:17 UTC, ronenh commented
This is still work in progress. The latest changes:
* Fix the broken links within the schema reference.
* Moves the GraphQL content into the `GraphQL API` section leaving the "Directory Guide" as a space for explaining the general concepts regardless of which API is used (GraphQL or gRPC).
* Added a little more content (more to come).

2022-08-24 18:01 UTC, ogazitt requested changes

2022-08-24 18:01 UTC, ogazitt commented on docs/directory-guide/concepts.mdx
> +h
dangling `h`

2022-08-24 18:01 UTC, ogazitt commented on docs/directory-guide/scenario.mdx
> +* `member`: In addition to viewer privgileges, members have permission to view all the data, add new products to the
privgileges -> privileges

2022-08-24 18:01 UTC, ogazitt commented on docs/directory-guide/scenario.mdx
> +    * Select the "Directory" section in the main navigation bar.
* New accounts already have a connection to the Citadel IDP and will display the five Citadel users. If you don't see them, follow the remainder of the steps below.

2022-08-24 18:01 UTC, ogazitt commented on docs/directory-guide/scenario.mdx
> +
I think we may want to include screenshots of where to get the tenant ID, the API key, and where in graphiql to put these (again, as a screenshot). Otherwise I think it's really hard to connect the dots.

2022-08-24 18:01 UTC, ogazitt commented on docs/directory-guide/types.mdx
> +We'll start witht the `viwer` relation.
viwer -> viewer

2022-08-24 18:01 UTC, ogazitt commented on docs/directory-guide/relations.mdx
> +:::note
I believe that ID's (and keys) for the Citadel users are all fixed...

My ID's for Rick are the same as yours. If that is not true for all time, perhaps we can use `target: {key: {key: "<rick-key>", type: {name: "user"}}}` or something like that, to use a stable key?

2022-08-24 22:09 UTC, ogazitt approved these changes

2022-08-24 22:10 UTC, merged